#!/bin/bash


CURRENTWORKSPACE=0

function handle {
  echo "$1"
  action="$(echo $1 |awk -F '>>' '{print $1}')"
  if [ "${action}" == "openwindow" ]; then
    data="$(echo $1 |awk -F "$action>>" '{print $2}')"
    ID="$(echo "$data" |awk -F ',' '{print $1}')"
    workspace="$(echo "$data" |awk -F ',' '{print $2}')"
    class="$(echo "$data" |awk -F ',' '{print $3}')"
    application_name="$(echo "$data" |awk -F ',' '{print $4}')"
    echo "$ID"
    echo "$class"
    echo "$workspace"
    echo "$application_name"
    if [ "$workspace" == "2" ]; then
#      hyprctl dispatch togglefloating "$ID"
      echo "Dispatched floating"
      fi
  fi
}


socat - UNIX-CONNECT:/tmp/hypr/$(echo $HYPRLAND_INSTANCE_SIGNATURE)/.socket2.sock | while read line; do handle $line; done
